-- Categories
insert into categories (id, label, icon, color, sort_order) values
  ('general', 'General Knowledge', 'Brain', '#FFC93C', 0),
  ('education', 'Education & School', 'GraduationCap', '#3FD5FF', 1),
  ('geography', 'Geography', 'Compass', '#4CC9F0', 2),
  ('history', 'History', 'Landmark', '#E07A5F', 3),
  ('science', 'Science', 'Atom', '#7C3AED', 4),
  ('technology', 'Technology', 'Cpu', '#3FD5FF', 5),
  ('gaming', 'Gaming', 'Gamepad2', '#B4FF39', 6),
  ('movies', 'Movies & Entertainment', 'Clapperboard', '#FF4E6A', 7),
  ('anime', 'Anime & Manga', 'Swords', '#F72585', 8),
  ('music', 'Music', 'Music', '#FFC93C', 9),
  ('sports', 'Sports', 'Dumbbell', '#4ADE80', 10),
  ('football', 'Football Specific', 'Goal', '#34D399', 11),
  ('puzzle', 'Brain & Puzzle', 'Puzzle', '#8B5CF6', 12),
  ('language', 'Language Learning', 'Languages', '#3FD5FF', 13),
  ('food', 'Food & Lifestyle', 'UtensilsCrossed', '#FB923C', 14),
  ('culture', 'Culture', 'Globe', '#F472B6', 15),
  ('fun', 'Fun Quiz Categories', 'PartyPopper', '#FF4E6A', 16),
  ('exam', 'Exam Preparation', 'ClipboardCheck', '#FFC93C', 17),
  ('career', 'Career Knowledge', 'Briefcase', '#3FD5FF', 18);

-- Sub-topics
insert into subtopics (id, category_id, label, sort_order) values
  ('world-facts', 'general', 'World Facts', 0),
  ('amazing-facts', 'general', 'Amazing Facts', 1),
  ('random-trivia', 'general', 'Random Trivia', 2),
  ('everyday-knowledge', 'general', 'Everyday Knowledge', 3),
  ('human-body-facts', 'general', 'Human Body Facts', 4),
  ('world-records', 'general', 'World Records', 5),
  ('famous-firsts', 'general', 'Famous Firsts', 6),
  ('inventions', 'general', 'Inventions', 7),
  ('discoveries', 'general', 'Discoveries', 8),
  ('historical-events', 'general', 'Historical Events', 9),
  ('famous-people', 'general', 'Famous People', 10),
  ('weird-facts', 'general', 'Weird Facts', 11),
  ('true-or-false-challenge', 'general', 'True or False Challenge', 12),
  ('basic-mathematics', 'education', 'Basic Mathematics', 0),
  ('algebra', 'education', 'Algebra', 1),
  ('geometry', 'education', 'Geometry', 2),
  ('calculus', 'education', 'Calculus', 3),
  ('statistics', 'education', 'Statistics', 4),
  ('physics', 'education', 'Physics', 5),
  ('chemistry', 'education', 'Chemistry', 6),
  ('biology', 'education', 'Biology', 7),
  ('basic-science', 'education', 'Basic Science', 8),
  ('environmental-science', 'education', 'Environmental Science', 9),
  ('english-grammar', 'education', 'English Grammar', 10),
  ('vocabulary', 'education', 'Vocabulary', 11),
  ('literature', 'education', 'Literature', 12),
  ('economics', 'education', 'Economics', 13),
  ('accounting', 'education', 'Accounting', 14),
  ('business-studies', 'education', 'Business Studies', 15),
  ('civic-education', 'education', 'Civic Education', 16),
  ('government', 'education', 'Government', 17),
  ('religious-studies', 'education', 'Religious Studies', 18),
  ('computer-science', 'education', 'Computer Science', 19),
  ('information-technology', 'education', 'Information Technology', 20),
  ('countries-of-the-world', 'geography', 'Countries of the World', 0),
  ('world-capitals', 'geography', 'World Capitals', 1),
  ('flags-quiz', 'geography', 'Flags Quiz', 2),
  ('continents', 'geography', 'Continents', 3),
  ('famous-landmarks', 'geography', 'Famous Landmarks', 4),
  ('rivers-and-lakes', 'geography', 'Rivers and Lakes', 5),
  ('mountains', 'geography', 'Mountains', 6),
  ('oceans-and-seas', 'geography', 'Oceans and Seas', 7),
  ('maps-challenge', 'geography', 'Maps Challenge', 8),
  ('african-countries', 'geography', 'African Countries', 9),
  ('african-capitals', 'geography', 'African Capitals', 10),
  ('african-geography', 'geography', 'African Geography', 11),
  ('european-countries', 'geography', 'European Countries', 12),
  ('european-geography', 'geography', 'European Geography', 13),
  ('asian-countries', 'geography', 'Asian Countries', 14),
  ('asian-geography', 'geography', 'Asian Geography', 15),
  ('north-america', 'geography', 'North America', 16),
  ('south-america', 'geography', 'South America', 17),
  ('ancient-civilizations', 'history', 'Ancient Civilizations', 0),
  ('world-war-history', 'history', 'World War History', 1),
  ('african-history', 'history', 'African History', 2),
  ('nigerian-history', 'history', 'Nigerian History', 3),
  ('european-history', 'history', 'European History', 4),
  ('american-history', 'history', 'American History', 5),
  ('ancient-egypt', 'history', 'Ancient Egypt', 6),
  ('roman-empire', 'history', 'Roman Empire', 7),
  ('greek-mythology', 'history', 'Greek Mythology', 8),
  ('medieval-history', 'history', 'Medieval History', 9),
  ('famous-leaders', 'history', 'Famous Leaders', 10),
  ('historical-battles', 'history', 'Historical Battles', 11),
  ('historical-mysteries', 'history', 'Historical Mysteries', 12),
  ('space-science', 'science', 'Space Science', 0),
  ('astronomy', 'science', 'Astronomy', 1),
  ('animals', 'science', 'Animals', 2),
  ('plants', 'science', 'Plants', 3),
  ('human-anatomy', 'science', 'Human Anatomy', 4),
  ('genetics', 'science', 'Genetics', 5),
  ('weather-and-climate', 'science', 'Weather and Climate', 6),
  ('earth-science', 'science', 'Earth Science', 7),
  ('medical-science', 'science', 'Medical Science', 8),
  ('psychology', 'science', 'Psychology', 9),
  ('ocean-science', 'science', 'Ocean Science', 10),
  ('computers', 'technology', 'Computers', 0),
  ('programming', 'technology', 'Programming', 1),
  ('artificial-intelligence', 'technology', 'Artificial Intelligence', 2),
  ('cybersecurity', 'technology', 'Cybersecurity', 3),
  ('internet-knowledge', 'technology', 'Internet Knowledge', 4),
  ('smartphones', 'technology', 'Smartphones', 5),
  ('gaming-technology', 'technology', 'Gaming Technology', 6),
  ('software', 'technology', 'Software', 7),
  ('hardware', 'technology', 'Hardware', 8),
  ('blockchain', 'technology', 'Blockchain', 9),
  ('robotics', 'technology', 'Robotics', 10),
  ('future-technology', 'technology', 'Future Technology', 11),
  ('video-games', 'gaming', 'Video Games', 0),
  ('mobile-games', 'gaming', 'Mobile Games', 1),
  ('pc-games', 'gaming', 'PC Games', 2),
  ('playstation-games', 'gaming', 'PlayStation Games', 3),
  ('xbox-games', 'gaming', 'Xbox Games', 4),
  ('nintendo-games', 'gaming', 'Nintendo Games', 5),
  ('minecraft', 'gaming', 'Minecraft', 6),
  ('fortnite', 'gaming', 'Fortnite', 7),
  ('call-of-duty', 'gaming', 'Call of Duty', 8),
  ('gta-series', 'gaming', 'GTA Series', 9),
  ('anime-games', 'gaming', 'Anime Games', 10),
  ('gaming-characters', 'gaming', 'Gaming Characters', 11),
  ('gaming-history', 'gaming', 'Gaming History', 12),
  ('movies', 'movies', 'Movies', 0),
  ('tv-shows', 'movies', 'TV Shows', 1),
  ('anime', 'movies', 'Anime', 2),
  ('cartoons', 'movies', 'Cartoons', 3),
  ('marvel-universe', 'movies', 'Marvel Universe', 4),
  ('dc-universe', 'movies', 'DC Universe', 5),
  ('disney', 'movies', 'Disney', 6),
  ('netflix-shows', 'movies', 'Netflix Shows', 7),
  ('horror-movies', 'movies', 'Horror Movies', 8),
  ('action-movies', 'movies', 'Action Movies', 9),
  ('comedy-movies', 'movies', 'Comedy Movies', 10),
  ('movie-quotes', 'movies', 'Movie Quotes', 11),
  ('famous-actors', 'movies', 'Famous Actors', 12),
  ('naruto', 'anime', 'Naruto', 0),
  ('one-piece', 'anime', 'One Piece', 1),
  ('dragon-ball', 'anime', 'Dragon Ball', 2),
  ('attack-on-titan', 'anime', 'Attack on Titan', 3),
  ('demon-slayer', 'anime', 'Demon Slayer', 4),
  ('jujutsu-kaisen', 'anime', 'Jujutsu Kaisen', 5),
  ('bleach', 'anime', 'Bleach', 6),
  ('death-note', 'anime', 'Death Note', 7),
  ('my-hero-academia', 'anime', 'My Hero Academia', 8),
  ('anime-characters', 'anime', 'Anime Characters', 9),
  ('anime-powers', 'anime', 'Anime Powers', 10),
  ('anime-battles', 'anime', 'Anime Battles', 11),
  ('music-history', 'music', 'Music History', 0),
  ('song-knowledge', 'music', 'Song Knowledge', 1),
  ('famous-singers', 'music', 'Famous Singers', 2),
  ('african-music', 'music', 'African Music', 3),
  ('nigerian-music', 'music', 'Nigerian Music', 4),
  ('k-pop', 'music', 'K-Pop', 5),
  ('hip-hop', 'music', 'Hip Hop', 6),
  ('rock-music', 'music', 'Rock Music', 7),
  ('classical-music', 'music', 'Classical Music', 8),
  ('music-instruments', 'music', 'Music Instruments', 9),
  ('guess-the-song', 'music', 'Guess The Song', 10),
  ('football-soccer', 'sports', 'Football/Soccer', 0),
  ('basketball', 'sports', 'Basketball', 1),
  ('tennis', 'sports', 'Tennis', 2),
  ('boxing', 'sports', 'Boxing', 3),
  ('mma', 'sports', 'MMA', 4),
  ('formula-1', 'sports', 'Formula 1', 5),
  ('olympics', 'sports', 'Olympics', 6),
  ('cricket', 'sports', 'Cricket', 7),
  ('wrestling', 'sports', 'Wrestling', 8),
  ('athletics', 'sports', 'Athletics', 9),
  ('sports-records', 'sports', 'Sports Records', 10),
  ('famous-athletes', 'sports', 'Famous Athletes', 11),
  ('sports-teams', 'sports', 'Sports Teams', 12),
  ('premier-league', 'football', 'Premier League', 0),
  ('uefa-champions-league', 'football', 'UEFA Champions League', 1),
  ('fifa-world-cup', 'football', 'FIFA World Cup', 2),
  ('football-players', 'football', 'Football Players', 3),
  ('football-clubs', 'football', 'Football Clubs', 4),
  ('football-history', 'football', 'Football History', 5),
  ('world-cup-winners', 'football', 'World Cup Winners', 6),
  ('football-rules', 'football', 'Football Rules', 7),
  ('stadiums', 'football', 'Stadiums', 8),
  ('transfer-history', 'football', 'Transfer History', 9),
  ('logic-questions', 'puzzle', 'Logic Questions', 0),
  ('riddles', 'puzzle', 'Riddles', 1),
  ('iq-tests', 'puzzle', 'IQ Tests', 2),
  ('memory-challenge', 'puzzle', 'Memory Challenge', 3),
  ('pattern-recognition', 'puzzle', 'Pattern Recognition', 4),
  ('math-puzzles', 'puzzle', 'Math Puzzles', 5),
  ('word-puzzles', 'puzzle', 'Word Puzzles', 6),
  ('detective-cases', 'puzzle', 'Detective Cases', 7),
  ('escape-room-style-questions', 'puzzle', 'Escape Room Style Questions', 8),
  ('critical-thinking', 'puzzle', 'Critical Thinking', 9),
  ('english-vocabulary', 'language', 'English Vocabulary', 0),
  ('english-grammar-2', 'language', 'English Grammar', 1),
  ('spelling', 'language', 'Spelling', 2),
  ('idioms', 'language', 'Idioms', 3),
  ('proverbs', 'language', 'Proverbs', 4),
  ('translation', 'language', 'Translation', 5),
  ('french-language', 'language', 'French Language', 6),
  ('spanish-language', 'language', 'Spanish Language', 7),
  ('arabic-language', 'language', 'Arabic Language', 8),
  ('japanese-language', 'language', 'Japanese Language', 9),
  ('world-foods', 'food', 'World Foods', 0),
  ('african-cuisine', 'food', 'African Cuisine', 1),
  ('nigerian-foods', 'food', 'Nigerian Foods', 2),
  ('cooking', 'food', 'Cooking', 3),
  ('fruits', 'food', 'Fruits', 4),
  ('drinks', 'food', 'Drinks', 5),
  ('food-history', 'food', 'Food History', 6),
  ('healthy-living', 'food', 'Healthy Living', 7),
  ('fashion', 'food', 'Fashion', 8),
  ('beauty', 'food', 'Beauty', 9),
  ('world-cultures', 'culture', 'World Cultures', 0),
  ('african-culture', 'culture', 'African Culture', 1),
  ('nigerian-culture', 'culture', 'Nigerian Culture', 2),
  ('traditions', 'culture', 'Traditions', 3),
  ('festivals', 'culture', 'Festivals', 4),
  ('languages', 'culture', 'Languages', 5),
  ('religions', 'culture', 'Religions', 6),
  ('mythology', 'culture', 'Mythology', 7),
  ('famous-customs', 'culture', 'Famous Customs', 8),
  ('guess-the-logo', 'fun', 'Guess The Logo', 0),
  ('guess-the-flag', 'fun', 'Guess The Flag', 1),
  ('guess-the-celebrity', 'fun', 'Guess The Celebrity', 2),
  ('guess-the-character', 'fun', 'Guess The Character', 3),
  ('guess-the-movie', 'fun', 'Guess The Movie', 4),
  ('guess-the-song-2', 'fun', 'Guess The Song', 5),
  ('who-am-i', 'fun', 'Who Am I?', 6),
  ('what-am-i', 'fun', 'What Am I?', 7),
  ('emoji-quiz', 'fun', 'Emoji Quiz', 8),
  ('picture-quiz', 'fun', 'Picture Quiz', 9),
  ('spot-the-difference', 'fun', 'Spot The Difference', 10),
  ('would-you-rather', 'fun', 'Would You Rather', 11),
  ('this-or-that', 'fun', 'This or That', 12),
  ('personality-quiz', 'fun', 'Personality Quiz', 13),
  ('survival-quiz', 'fun', 'Survival Quiz', 14),
  ('waec-preparation', 'exam', 'WAEC Preparation', 0),
  ('neco-preparation', 'exam', 'NECO Preparation', 1),
  ('jamb-preparation', 'exam', 'JAMB Preparation', 2),
  ('sat-preparation', 'exam', 'SAT Preparation', 3),
  ('ielts-preparation', 'exam', 'IELTS Preparation', 4),
  ('toefl-preparation', 'exam', 'TOEFL Preparation', 5),
  ('anatomy', 'career', 'Anatomy', 0),
  ('medical-terms', 'career', 'Medical Terms', 1),
  ('health-science', 'career', 'Health Science', 2),
  ('engineering-basics', 'career', 'Engineering Basics', 3),
  ('mechanical-engineering', 'career', 'Mechanical Engineering', 4),
  ('electrical-engineering', 'career', 'Electrical Engineering', 5),
  ('civil-engineering', 'career', 'Civil Engineering', 6),
  ('legal-terms', 'career', 'Legal Terms', 7),
  ('government-law', 'career', 'Government Law', 8),
  ('legal-knowledge', 'career', 'Legal Knowledge', 9),
  ('entrepreneurship', 'career', 'Entrepreneurship', 10),
  ('marketing', 'career', 'Marketing', 11),
  ('finance', 'career', 'Finance', 12),
  ('management', 'career', 'Management', 13),
  ('programming-languages', 'career', 'Programming Languages', 14),
  ('coding-concepts', 'career', 'Coding Concepts', 15),
  ('software-development', 'career', 'Software Development', 16),
  ('aircraft-knowledge', 'career', 'Aircraft Knowledge', 17),
  ('aviation-history', 'career', 'Aviation History', 18),
  ('flight-basics', 'career', 'Flight Basics', 19);

-- Questions
insert into questions (subtopic_id, question, options, correct, explain, sort_order) values
  ('world-facts', 'Which is the largest country by land area?', '["China","USA","Russia","Canada"]'::jsonb, 2, 'Russia spans over 17 million square kilometers.', 0),
  ('world-facts', 'What is the most spoken native language in the world?', '["English","Mandarin Chinese","Hindi","Spanish"]'::jsonb, 1, 'Mandarin has the most native speakers worldwide.', 1),
  ('world-facts', 'Which country has the most time zones?', '["USA","Russia","France","China"]'::jsonb, 2, 'Including overseas territories, France spans 12 time zones.', 2),
  ('world-facts', 'What is the tallest building in the world (as of the 2020s)?', '["Shanghai Tower","Burj Khalifa","One World Trade Center","Petronas Towers"]'::jsonb, 1, 'The Burj Khalifa in Dubai stands at 828 meters.', 3),
  ('world-facts', 'Which currency is used in Japan?', '["Won","Yuan","Yen","Ringgit"]'::jsonb, 2, 'The Japanese Yen has been used since 1871.', 4),
  ('basic-mathematics', 'What is 12 × 8?', '["96","86","104","108"]'::jsonb, 0, '12 × 8 = 96.', 0),
  ('basic-mathematics', 'What is the square root of 144?', '["11","12","13","14"]'::jsonb, 1, '12 × 12 = 144.', 1),
  ('basic-mathematics', 'What is 15% of 200?', '["20","25","30","35"]'::jsonb, 2, '15% of 200 = 0.15 × 200 = 30.', 2),
  ('basic-mathematics', 'Which number is a prime number?', '["21","27","29","33"]'::jsonb, 2, '29 has no divisors other than 1 and itself.', 3),
  ('basic-mathematics', 'What is the value of π (pi) to two decimal places?', '["3.12","3.14","3.16","3.18"]'::jsonb, 1, 'Pi is approximately 3.14159.', 4),
  ('countries-of-the-world', 'Which country has the most population?', '["USA","India","China","Indonesia"]'::jsonb, 1, 'India overtook China in population in 2023.', 0),
  ('countries-of-the-world', 'What is the smallest country in the world?', '["Monaco","San Marino","Vatican City","Liechtenstein"]'::jsonb, 2, 'Vatican City is about 0.44 square kilometers.', 1),
  ('countries-of-the-world', 'Which country is known as the Land of the Rising Sun?', '["China","South Korea","Japan","Thailand"]'::jsonb, 2, 'Japan''s name translates to ''origin of the sun''.', 2),
  ('countries-of-the-world', 'Which country has the most natural lakes?', '["USA","Canada","Russia","Finland"]'::jsonb, 1, 'Canada holds more freshwater lakes than any other country.', 3),
  ('countries-of-the-world', 'Which African country was never colonized?', '["Kenya","Ethiopia","Nigeria","Ghana"]'::jsonb, 1, 'Ethiopia successfully resisted colonization, aside from a brief Italian occupation.', 4),
  ('ancient-egypt', 'What were Egyptian pyramids primarily built as?', '["Temples","Tombs for pharaohs","Palaces","Granaries"]'::jsonb, 1, 'Pyramids served as elaborate tombs for pharaohs and their treasures.', 0),
  ('ancient-egypt', 'Which river was central to ancient Egyptian civilization?', '["Tigris","Euphrates","Nile","Jordan"]'::jsonb, 2, 'The Nile''s annual floods enabled agriculture in Egypt.', 1),
  ('ancient-egypt', 'Who was the famous boy pharaoh whose tomb was found nearly intact in 1922?', '["Ramses II","Tutankhamun","Akhenaten","Thutmose III"]'::jsonb, 1, 'Howard Carter discovered Tutankhamun''s tomb in the Valley of the Kings.', 2),
  ('ancient-egypt', 'What writing system did ancient Egyptians use?', '["Cuneiform","Hieroglyphics","Runes","Sanskrit"]'::jsonb, 1, 'Hieroglyphics combined logographic and alphabetic elements.', 3),
  ('ancient-egypt', 'What was the Great Sphinx built with the body of?', '["An eagle","A lion","A bull","A ram"]'::jsonb, 1, 'The Sphinx has the body of a lion and the head of a pharaoh.', 4),
  ('space-science', 'What is the closest star to Earth?', '["Proxima Centauri","The Sun","Sirius","Betelgeuse"]'::jsonb, 1, 'The Sun is about 8 light-minutes away from Earth.', 0),
  ('space-science', 'Which planet has the most moons (as currently known)?', '["Jupiter","Saturn","Uranus","Neptune"]'::jsonb, 1, 'Saturn has surpassed Jupiter with over 140 confirmed moons.', 1),
  ('space-science', 'What is a light-year a measure of?', '["Time","Distance","Brightness","Mass"]'::jsonb, 1, 'A light-year measures the distance light travels in one year.', 2),
  ('space-science', 'What galaxy do we live in?', '["Andromeda","Triangulum","Milky Way","Whirlpool"]'::jsonb, 2, 'Our solar system sits in the Milky Way galaxy.', 3),
  ('space-science', 'Which spacecraft first landed humans on the Moon?', '["Apollo 11","Gemini 8","Sputnik 1","Voyager 1"]'::jsonb, 0, 'Apollo 11 landed Neil Armstrong and Buzz Aldrin in 1969.', 4),
  ('artificial-intelligence', 'What does ''AI'' stand for?', '["Automated Interface","Artificial Intelligence","Applied Informatics","Algorithmic Input"]'::jsonb, 1, 'AI refers to machines simulating human-like intelligence.', 0),
  ('artificial-intelligence', 'What is a ''neural network'' loosely modeled on?', '["Computer circuits","The human brain","Ant colonies","The internet"]'::jsonb, 1, 'Neural networks are inspired by interconnected neurons in the brain.', 1),
  ('artificial-intelligence', 'What term describes an AI generating text word by word based on patterns?', '["Compiling","Rendering","Language modeling","Indexing"]'::jsonb, 2, 'Language models predict likely next words based on training patterns.', 2),
  ('artificial-intelligence', 'What is ''machine learning'' a subset of?', '["Robotics","Artificial Intelligence","Cybersecurity","Cloud computing"]'::jsonb, 1, 'Machine learning is a core approach within the broader AI field.', 3),
  ('artificial-intelligence', 'What do we call AI-generated images, video, or text as a category?', '["Generative AI","Static AI","Passive AI","Manual AI"]'::jsonb, 0, 'Generative AI creates new content rather than just analyzing existing data.', 4),
  ('video-games', 'Which company created the Mario franchise?', '["Sega","Sony","Nintendo","Capcom"]'::jsonb, 2, 'Nintendo has published Mario games since 1981.', 0),
  ('video-games', 'What year was the original PlayStation released?', '["1993","1994","1996","1998"]'::jsonb, 1, 'Sony released the PlayStation in Japan in December 1994.', 1),
  ('video-games', 'In gaming, what does ''FPS'' commonly stand for?', '["Fast Player Speed","First-Person Shooter","Full Party System","Final Player Score"]'::jsonb, 1, 'FPS games are played from the character''s own viewpoint.', 2),
  ('video-games', 'Which game popularized the ''battle royale'' genre widely?', '["Minecraft","Fortnite","Tetris","The Sims"]'::jsonb, 1, 'Fortnite brought battle royale to mainstream global popularity from 2017.', 3),
  ('video-games', 'What is the best-selling video game of all time?', '["Tetris","Minecraft","GTA V","Wii Sports"]'::jsonb, 1, 'Minecraft has sold over 300 million copies across all platforms.', 4),
  ('marvel-universe', 'What is Tony Stark''s superhero identity?', '["Captain America","Iron Man","Thor","Hawkeye"]'::jsonb, 1, 'Tony Stark builds a powered suit of armor to become Iron Man.', 0),
  ('marvel-universe', 'What metal makes up Captain America''s shield?', '["Adamantium","Vibranium","Titanium","Uru"]'::jsonb, 1, 'The shield is made of a vibranium-steel alloy.', 1),
  ('marvel-universe', 'Who is the main villain in ''Avengers: Infinity War''?', '["Loki","Ultron","Thanos","Red Skull"]'::jsonb, 2, 'Thanos seeks the Infinity Stones to wipe out half of all life.', 2),
  ('marvel-universe', 'What is the name of Thor''s hammer?', '["Stormbreaker","Mjolnir","Gungnir","Excalibur"]'::jsonb, 1, 'Mjolnir is Thor''s iconic enchanted hammer.', 3),
  ('marvel-universe', 'Which team does Spider-Man famously join in the comics?', '["X-Men","Avengers","Fantastic Four","Guardians of the Galaxy"]'::jsonb, 1, 'Spider-Man has been a prominent Avengers member.', 4),
  ('naruto', 'What is the name of Naruto''s village?', '["Konohagakure","Sunagakure","Kirigakure","Iwagakure"]'::jsonb, 0, 'Naruto hails from the Hidden Leaf Village, Konohagakure.', 0),
  ('naruto', 'What creature is sealed inside Naruto?', '["Two-Tails","Nine-Tails Fox","Five-Tails","One-Tail"]'::jsonb, 1, 'The Nine-Tailed Fox, Kurama, is sealed within Naruto.', 1),
  ('naruto', 'What is Naruto''s signature technique?', '["Sharingan","Rasengan","Chidori","Amaterasu"]'::jsonb, 1, 'The Rasengan is a spiraling chakra sphere Naruto masters early on.', 2),
  ('naruto', 'Who is Naruto''s childhood rival and best friend?', '["Kakashi","Sasuke Uchiha","Shikamaru","Rock Lee"]'::jsonb, 1, 'Sasuke Uchiha shares a deep rivalry and bond with Naruto.', 3),
  ('naruto', 'What rank does Naruto ultimately achieve?', '["Chunin","Jonin","Hokage","Anbu"]'::jsonb, 2, 'Naruto achieves his lifelong dream of becoming Hokage.', 4),
  ('music-history', 'Which decade is often called the birth of rock and roll?', '["1930s","1950s","1970s","1990s"]'::jsonb, 1, 'Rock and roll emerged and gained mainstream popularity in the 1950s.', 0),
  ('music-history', 'Which composer went deaf but continued composing symphonies?', '["Mozart","Bach","Beethoven","Chopin"]'::jsonb, 2, 'Beethoven composed some of his greatest works after losing his hearing.', 1),
  ('music-history', 'Which band is known as ''The Fab Four''?', '["The Rolling Stones","The Beatles","Queen","Led Zeppelin"]'::jsonb, 1, 'The Beatles were nicknamed the Fab Four.', 2),
  ('music-history', 'What genre originated in Jamaica in the late 1960s?', '["Reggae","Blues","Jazz","Disco"]'::jsonb, 0, 'Reggae developed in Jamaica, popularized globally by Bob Marley.', 3),
  ('music-history', 'Which artist is known as the ''King of Pop''?', '["Prince","Elvis Presley","Michael Jackson","Stevie Wonder"]'::jsonb, 2, 'Michael Jackson earned the title through his massive global influence.', 4),
  ('football-soccer', 'How many players are on a football team on the field?', '["9","10","11","12"]'::jsonb, 2, 'Each team fields 11 players, including the goalkeeper.', 0),
  ('football-soccer', 'How long is a standard football match (excluding stoppage time)?', '["60 minutes","80 minutes","90 minutes","100 minutes"]'::jsonb, 2, 'A standard match consists of two 45-minute halves.', 1),
  ('football-soccer', 'Which country has won the most FIFA World Cups?', '["Germany","Argentina","Brazil","Italy"]'::jsonb, 2, 'Brazil has won the World Cup 5 times.', 2),
  ('football-soccer', 'What card signals a player''s ejection from a match?', '["Yellow card","Red card","Blue card","Green card"]'::jsonb, 1, 'A red card results in an immediate send-off.', 3),
  ('football-soccer', 'What is it called when a player scores three goals in one match?', '["Double","Hat-trick","Triple crown","Grand slam"]'::jsonb, 1, 'Scoring three goals in a single game is called a hat-trick.', 4),
  ('fifa-world-cup', 'How often is the FIFA World Cup held?', '["Every 2 years","Every 3 years","Every 4 years","Every 5 years"]'::jsonb, 2, 'The World Cup has been held every 4 years since 1930 (barring wartime gaps).', 0),
  ('fifa-world-cup', 'Which country hosted the first FIFA World Cup in 1930?', '["Brazil","Uruguay","France","Italy"]'::jsonb, 1, 'Uruguay hosted and won the inaugural World Cup.', 1),
  ('fifa-world-cup', 'Who won the 2018 FIFA World Cup?', '["Croatia","Belgium","France","England"]'::jsonb, 2, 'France defeated Croatia 4-2 in the final.', 2),
  ('fifa-world-cup', 'Which player has scored the most World Cup goals in history?', '["Pelé","Miroslav Klose","Ronaldo Nazário","Lionel Messi"]'::jsonb, 1, 'Germany''s Miroslav Klose holds the record with 16 goals.', 3),
  ('fifa-world-cup', 'Which country won the 2022 FIFA World Cup?', '["France","Argentina","Brazil","Croatia"]'::jsonb, 1, 'Argentina won on penalties after a 3-3 draw with France.', 4),
  ('riddles', 'I speak without a mouth and hear without ears. What am I?', '["A ghost","An echo","A shadow","A dream"]'::jsonb, 1, 'An echo repeats sound without having a mouth or ears.', 0),
  ('riddles', 'The more you take, the more you leave behind. What am I?', '["Time","Money","Footsteps","Memories"]'::jsonb, 2, 'Each step you take leaves a footprint behind.', 1),
  ('riddles', 'What has keys but no locks, space but no room, and you can enter but not go inside?', '["A house","A keyboard","A map","A piano"]'::jsonb, 1, 'A keyboard has keys and a space bar, and you can ''enter'' with the Enter key.', 2),
  ('riddles', 'What comes once in a minute, twice in a moment, but never in a thousand years?', '["The letter M","A second","A heartbeat","A blink"]'::jsonb, 0, 'The letter ''M'' appears once in ''minute'' and twice in ''moment''.', 3),
  ('riddles', 'What has a neck but no head?', '["A shirt","A bottle","A road","A guitar"]'::jsonb, 1, 'A bottle has a neck but no head.', 4),
  ('english-vocabulary', 'What is a synonym for ''happy''?', '["Joyful","Furious","Tired","Anxious"]'::jsonb, 0, '''Joyful'' means feeling or expressing great happiness.', 0),
  ('english-vocabulary', 'What does ''benevolent'' mean?', '["Cruel","Kind and generous","Confused","Wealthy"]'::jsonb, 1, 'Benevolent describes a well-meaning, kind disposition.', 1),
  ('english-vocabulary', 'What is the antonym of ''ancient''?', '["Modern","Old","Historic","Aged"]'::jsonb, 0, '''Modern'' is the opposite of ''ancient''.', 2),
  ('english-vocabulary', 'What does ''ubiquitous'' mean?', '["Rare","Present everywhere","Invisible","Expensive"]'::jsonb, 1, 'Ubiquitous means found or seeming to be found everywhere.', 3),
  ('english-vocabulary', 'What is a synonym for ''meticulous''?', '["Careless","Careful and precise","Lazy","Hasty"]'::jsonb, 1, 'Meticulous describes showing great attention to detail.', 4),
  ('nigerian-foods', 'What is the main ingredient in Jollof rice?', '["Wheat","Rice","Yam","Beans"]'::jsonb, 1, 'Jollof rice is a rice dish cooked in a tomato-based sauce.', 0),
  ('nigerian-foods', 'What is ''suya'' typically made from?', '["Fish","Grilled spiced meat skewers","Boiled plantain","Bean cakes"]'::jsonb, 1, 'Suya is skewered meat coated in a spicy peanut-based seasoning.', 1),
  ('nigerian-foods', 'What leafy vegetable is used in Nigerian egusi soup along with ground melon seeds?', '["Spinach only","Bitterleaf or ugu (pumpkin leaves)","Cabbage","Lettuce"]'::jsonb, 1, 'Egusi soup is commonly made with ugu or bitterleaf alongside ground melon seeds.', 2),
  ('nigerian-foods', 'What is ''moin moin'' made from?', '["Ground beans","Ground rice","Ground corn","Ground yam"]'::jsonb, 0, 'Moin moin is a steamed pudding made from peeled black-eyed peas.', 3),
  ('nigerian-foods', 'Which Nigerian snack is deep-fried and made from ripe plantain?', '["Akara","Dodo","Chin chin","Puff puff"]'::jsonb, 1, 'Dodo refers to fried ripe plantain slices.', 4),
  ('world-cultures', 'In Japan, what is the traditional tea ceremony called?', '["Kabuki","Chanoyu","Ikebana","Origami"]'::jsonb, 1, 'Chanoyu is the formal Japanese tea ceremony.', 0),
  ('world-cultures', 'What is the traditional Scottish garment worn by men called?', '["Kimono","Kilt","Sarong","Poncho"]'::jsonb, 1, 'The kilt is a knee-length garment tied to Scottish Highland dress.', 1),
  ('world-cultures', 'Diwali, the festival of lights, is major in which culture?', '["Japanese","Indian","Mexican","Greek"]'::jsonb, 1, 'Diwali is widely celebrated across Indian and South Asian cultures.', 2),
  ('world-cultures', 'What is the traditional Mexican celebration honoring deceased loved ones called?', '["Cinco de Mayo","Día de los Muertos","Carnaval","Las Posadas"]'::jsonb, 1, 'Día de los Muertos (Day of the Dead) honors deceased family members.', 3),
  ('world-cultures', 'In many West African cultures, what is ''kente'' known for?', '["A style of drumming","A woven, colorful fabric","A traditional dance","A type of food"]'::jsonb, 1, 'Kente is a famous hand-woven textile originating from Ghana.', 4),
  ('guess-the-flag', 'Which country''s flag is a red circle centered on a white background?', '["South Korea","Japan","Bangladesh","Palau"]'::jsonb, 1, 'Japan''s flag, the Nisshoki, features a red sun disc on white.', 0),
  ('guess-the-flag', 'Which flag features a red maple leaf on a white background with red bars?', '["Canada","Switzerland","Austria","Peru"]'::jsonb, 0, 'Canada''s flag has featured the red maple leaf since 1965.', 1),
  ('guess-the-flag', 'Which country''s flag has green, white, and green vertical stripes?', '["Italy","Nigeria","Mexico","Hungary"]'::jsonb, 1, 'Nigeria''s flag is green-white-green, symbolizing agriculture and peace.', 2),
  ('guess-the-flag', 'Which flag consists of a blue field with a circle of 12 gold stars?', '["United Nations","European Union","NATO","African Union"]'::jsonb, 1, 'The EU flag''s 12 stars represent unity, not the number of member states.', 3),
  ('guess-the-flag', 'Which country''s flag features a large red dot representing the sun rising over its striped field?', '["Bangladesh","Vietnam","Turkey","Nepal"]'::jsonb, 0, 'Bangladesh''s flag has a red disc slightly off-center on a green field.', 4),
  ('jamb-preparation', 'In JAMB-style English, which word is spelled correctly?', '["Recieve","Receive","Receve","Receeve"]'::jsonb, 1, '''Receive'' follows the ''i before e except after c'' pattern correctly here.', 0),
  ('jamb-preparation', 'If x + 5 = 12, what is x?', '["5","6","7","8"]'::jsonb, 2, 'Subtracting 5 from both sides gives x = 7.', 1),
  ('jamb-preparation', 'Which gas is most abundant in Earth''s atmosphere?', '["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"]'::jsonb, 1, 'Nitrogen makes up about 78% of the atmosphere.', 2),
  ('jamb-preparation', 'Choose the correctly punctuated sentence.', '["Its a nice day.","It''s a nice day.","Its'' a nice day.","It, is a nice day."]'::jsonb, 1, '''It''s'' is the correct contraction of ''it is''.', 3),
  ('jamb-preparation', 'What is the past tense of ''go''?', '["Goed","Went","Gone","Going"]'::jsonb, 1, '''Went'' is the simple past tense of ''go''.', 4),
  ('medical-terms', 'What does the prefix ''cardio-'' relate to?', '["Lungs","Heart","Brain","Kidneys"]'::jsonb, 1, '''Cardio-'' relates to the heart, as in cardiology.', 0),
  ('medical-terms', 'What does ''dermatology'' study?', '["Bones","Skin","Blood","Nerves"]'::jsonb, 1, 'Dermatology is the branch of medicine focused on skin.', 1),
  ('medical-terms', 'What does ''tachycardia'' refer to?', '["Slow heart rate","Fast heart rate","Low blood pressure","High blood sugar"]'::jsonb, 1, 'Tachycardia describes an abnormally fast heart rate.', 2),
  ('medical-terms', 'What organ does ''hepatic'' refer to?', '["Liver","Heart","Lungs","Stomach"]'::jsonb, 0, '''Hepatic'' relates to the liver, as in hepatitis.', 3),
  ('medical-terms', 'What does the suffix ''-itis'' typically mean?', '["Removal of","Inflammation of","Study of","Enlargement of"]'::jsonb, 1, '''-itis'' denotes inflammation, as in arthritis or appendicitis.', 4);
